command:
  - "python"
  - "-m"
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8000"
  - "--server.address=0.0.0.0"
  - "--server.headless=true"
  - "--server.enableCORS=false"
  - "--server.enableXsrfProtection=false"

env:
  - name: CATALOG
    value: "ericos_catalog"
  - name: SCHEMA
    value: "godata"
  - name: TABLE
    value: "nfcom_data"
  - name: JOB_NAME
    value: "NFCom - Export XML Files"
  - name: LOG_LEVEL
    value: "INFO"   # Change to DEBUG for verbose output in the Logs tab
